### ISSUE TITLE
Error detail from failing test not included in log

### ISSUE THREAD

**Issue by dmatesic** [brutaldev/logfile-grunt#2]
So for example, if one of my mocha tests fails, the stack trace and other error details are not appended to the grunt log file.

If I run grunt without grunt log and output the console log to a temp file (i.e. "grunt > temp.txt"), these errors are not added to temp.txt as well. So I'm not sure if this is something that can be solved in logfile-grunt.

**Comment by brutaldev** [comment]
This can certainly be fixed. The console has multiple streams where text can be written (`stdout` and `stderr`). This plugin only hooks into `stdout` so any tasks writing to `stderr` will not be caught. Similarly in the output script you provided, it will only write `stdout` to the text file, to write both streams you should change it to `grunt > temp.txt 2>&1`

**Comment by brutaldev** [comment]
This has been fixed in v0.1.6 and should be getting published to NPM any second now.

**Comment by dmatesic** [comment]
That was quick! Thanks!
