### ISSUE TITLE
Using with a console progress bar module

### ISSUE THREAD

**Issue by johowie** [brutaldev/logfile-grunt#9]
I just tried using logfile-grunt with `progress` (on npm) which is a module for outputting a progress bar. As i anticipated the continually updating progress bar results in making a mess of the logfile output.
Is there a way to exclude the output generated by progress from the logfile ?
Or any other recommendations for both logging output to console, whilst also using some sort of progress indication that ideally doesn't appear in the logfile ?

**Comment by johowie** [comment]
here's an example of the start of some of the log file:

Running "uploadImages:people" (uploadImages) task
ImageUploader initializing....

uploading images
NUMBER OF IMAGE FILES: 406

[1G-----------------------------------------------------------------------------------------------------------------------------------------------------[0K[1G=----------------------------------------------------------------------------------------------------------------------------------------------------[0K[1G==---------------------------------------------------------------------------------------------------------------------------------------------------[0K[1G===--------------------------------------------------------------------------------------------------------------------------------------------------[0K[1G====-------------------------------------------------------------------------------------------------------------------------------------------------[0K[1G=====------------------------------------------------------------------------------------------------------------------------------------------------[0K[1G======--------------------------------------------------------------------------------------------------




etc etc

**Comment by brutaldev** [comment]
There is currently no way of excluding certain text from going into the log, it simply captures everything being written to the console and writes that to file.

You could check for this particular progress pattern in the conditional check on [line 63](https://github.com/brutaldev/logfile-grunt/blob/master/logfile-grunt.js#L63) before it writes the text to file. A long term solution would be to provide a regular expression option to filter out text you do not want to appear in the log.

**Comment by johowie** [comment]
thanks for the reply. the regex option sounds like a good idea. in my case i'd be looking at using an expression such as /\x1b\[1G(.*)\x1b\[0K/g to remove the progress bar effects.
i will look into implementing a regex filter if time permits

**Comment by brutaldev** [comment]
Pretty simple little feature so I added it for you. Let me know how that works out.

**Comment by johowie** [comment]
Hi Brutaldev,
I was away from my computer and am so happy to come back and see there is an early christmas present ! I will test during today, Thanks
